# Generated by Django 3.2.10 on 2022-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='day',
            field=models.CharField(default='.', max_length=1000),
        ),
    ]
